### ISSUE TITLE
Issue with Channel Mapping and Reference bank

### ISSUE THREAD

**Issue by koreign** [open-ephys/GUI#269]
Dear All,

    Thank you again for the great work. I noticed a quite disturbing problem while playing with the channel mapping module:

The module is used for:
1. reordering channels
2. activate deactivate channels
3. organize reference banks

     The issue:
1. I used the simple chain: file reader (with provided cortext rec) -> channel map -> lfp viewer
2. in channel mapping: i reordered channel No-5 to the first position (and in the param tab 5 also shifted to first position) - nothing wrong so far
3. I selected the bank A and added the 4 first channels (5 1 2 3).
4. now I chose the reference to be channel No-5 (first channel in param, also namce 5) and magically channel N0-5 was not 0 (chan1 in lfp viewer) but the second channel in the lfp viewer which should correspond to channel 1 after remapping.
5. if one choses the channel 4 in params of the channel mapping module (in position 5), now chan1 in lfp viewer (true channel No5) will be 0.
 
    Now this is both confusing and could results in huge problem, but it seems to be a simple fix:
The params tab of the channel mapping is reordering the name of the channels after remapping, without actually changing the underlying true channel.
the fix needed: either dont change the channel order in params (as is, then each channel correspond to itself), either relink the channel to itself after reordering both channel and params.

   I realized that my previous install <=0.3.3 did not have that problem only the most recent binary 0.3.4 i presume (by the way, how can we know the version from the gui ? on MacOsX I couldn't find it sorry)

Hope I am understanding it right. (since it is in the binary it should be fix asap for actual experiments)

Koreign

**Comment by aacuevas** [comment]
It is definitely a bug, probably derived from how we changed some underlying methods to be able to support multiple sources with different sample rates, some index must have been moved, I'll look at it asap.

To know the version of the GUI, you can look at the bottom right corner of the "Graph" visualizer tab.

**Comment by aacuevas** [comment]
Should be fixed now in the latest version of the source code.

**Comment by koreign** [comment]
Thanks. I still have some trouble with compiling so I will have to wait until the next binary release for now.
